/**:
  ros__parameters:
    visualize: true

    # Topics for all lidars
    lidar_topics: [main, left, right]
    target_frame_id: main
    # path for point clouds in pcd format. Structure: /pcd_directory/<lidar_name>.pcd
    pcd_directory: /data/demo1/

    # logging output
    results_file: demo_results.txt

    # calibration results are stored here (path relative to the dir with multi_lidar_calibrator.py)
    output_dir: /output_1/